### ISSUE TITLE
STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine

### ISSUE THREAD

**Issue by MichaelVanHouHei** [x-nas/WinPacketsEdit#1]
开始注入目标进程 =>> LdVBoxHeadless
出现错误：STATUS_INTERNAL_ERROR: Unknown error in injected C++ completion routine. (Code: 15)
作者你好 , 雷電模擬器注入失敗 , 我自己用C#調用easyhook也出現同樣的問題

**Comment by x-nas** [comment]
你试试看用管理员权限启动C#然后再调用easyhook

**Comment by MichaelVanHouHei** [comment]
就是管理員開的哦
試過用powershell unlock所有restrictions ，加上管理員權限還是inject不了
自已之前用easyhook 做也失敗，然後這個project 測試一下也失敗 不知道是不是我window10的版本問題

**Comment by x-nas** [comment]
这个问题我在easyhook的git上看到有很多人提出来了，作者也没给一个明确的说法，我的win10是企业版打了最新的补丁，暂时还没碰到这个问题，我感觉还是跟权限有关，你再试试把easyhook注册到GAC看

**Comment by MichaelVanHouHei** [comment]
感謝回覆 小弟考完試後研究一下 , 希望可以加入幫忙開發

**Comment by MichaelVanHouHei** [comment]
for those people who suffer this problem , probably as  @x-nas mentioned , just simply copy the easyhook dll to C:\Windows\assembly or using gacutil /i [easyhook dll] for solve this problem

**Comment by MichaelVanHouHei** [comment]
![image](https://user-images.githubusercontent.com/17375554/144147093-42fb6d27-cb55-404c-b6ae-1dfc65b52caa.png)

**Comment by x-nas** [comment]
Nice Work！

**Comment by MichaelVanHouHei** [comment]
作者 , 如果把wpf 做成dll inject進去發現找不到entry point , 經網上查找我改了app.xaml的build action 也不行 , 想請教一下作者如果是使用wpf如果做到?
