### ISSUE TITLE
请问大佬  最新24版  下载器无法连接服务器~~

### ISSUE THREAD

**Issue by xue1987** [x-nas/WinPacketsEdit#10]
请问大佬  最新24版  下载器无法连接服务器~~

**Comment by xue1987** [comment]
大佬  请问还能下载吗??

**Comment by flymeqy** [comment]
应该是噶了，服务器噶了

**Comment by xue1987** [comment]
大佬有绿色版吗~~~给一个撒   服务器噶了  下载不到了~~

**Comment by fortheoverlord** [comment]
同求下载

**Comment by xue1987** [comment]
> 同求下载

服务器好啦   我都下载了

**Comment by ALuoggg** [comment]
> > 同求下载
> 
> 服务器好啦 我都下载了

可以分享一下吗，链接打不开了，谢谢qq1472190350

**Comment by x-nas** [comment]
服务器是我家里的台式电脑，不能保证24小时在线，如果无法访问可以过一段时间再试试
