### ISSUE TITLE
大佬拦截怎么实现啊

### ISSUE THREAD

**Issue by sqq200111** [x-nas/WinPacketsEdit#11]
我有一个想法，就是根据内容拦截，跟WPE一样，有一个动作是拦截，就是匹配到包内容里面的特征以后去拦截，我不太懂这个ws2所以想问一下那个拦截用什么函数。

**Comment by x-nas** [comment]
主窗体有个“拦截”的勾选框，需要拦截什么类型的包就勾选那个类型前面的复选框就可以了
