### ISSUE TITLE
下载失败，连续很多天一直这样

### ISSUE THREAD

**Issue by ALuoggg** [x-nas/WinPacketsEdit#13]
如题，连续多天一直提示下载失败，请问可以分享一下免安装程序的吗，真的很想要。qq1472190350，有小费。谢谢😘😘😘

**Comment by ALuoggg** [comment]
![Uploading 20230415-140756.png…]()

**Comment by ALuoggg** [comment]
![20230415-140756](https://user-images.githubusercontent.com/125128477/232189332-937fdf83-190f-4fe3-9e6d-7debb8feaae6.png)
一直这样子

**Comment by x-nas** [comment]
服务器是我家里的电脑，有时候会不在线，安装exe版本后，就算服务器离线也可以用的
Download setup.exe: https://www.x-nas.com/wpe/publish.htm
