### ISSUE TITLE
在发送列表在备注定义快捷键？

### ISSUE THREAD

**Issue by MOYSKYC** [x-nas/WinPacketsEdit#16]
可不可以根据备注添加全局快捷键的功能？

比如
  在序号01-05备注写上 "|Alt & 1|分类1" 实现按alt+1发送1-5或者选中1-5
  在序号06-10备注写上 "|Alt & 2|分类2" 实现按alt+2发送6-10或者选中6-10

**Comment by x-nas** [comment]
很好的建议，争取下个版本安排上
