### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by massagesalan** [x-nas/WinPacketsEdit#6]
Thank you, this is a very useful tool.
Will you develop a similar wpe filter function in the future?
No filter function is the only small regret of this tool
Thank you very much!

**Comment by x-nas** [comment]
OK, I will arrange the development of filter function asap！

**Comment by massagesalan** [comment]
> OK, I will arrange the development of filter function asap！

Thank you, you are a very good developer.
Looking forward to your update!

**Comment by x-nas** [comment]
能否把“日志”中的滤镜信息发出来看下，里面有过滤是否成功的信息

**Comment by lovesoheart** [comment]
> 能否把“日志”中的滤镜信息发出来看下，里面有过滤是否成功的信息

我有按滤镜的应用，但是没有在日志中显示任何成功或者失败的讯息。
封包也无法替换成功

![1648815333294](https://user-images.githubusercontent.com/90022205/161261786-d73c3cf2-4f67-4ce6-87ba-2f6fe6d1631d.jpg)

**Comment by lovesoheart** [comment]
> ![33](https://user-images.githubusercontent.com/67667226/161263327-16a6c2c7-c783-4b47-9d67-831c2a2894c4.jpg)
> 
> 你的界面有问题，滤镜前面有勾选框没有显示出来吧？ 需要勾选中后才能启用滤镜
我明白了，介面没有勾选的功能显示。
有些显示不全
![feng](https://user-images.githubusercontent.com/90022205/161264277-0c79e62e-bb71-4cdc-a77b-1d80c8e987e7.jpg)

**Comment by x-nas** [comment]
你试试看把字体调小点，分辨率调大点？ 如果还不行的话，把你用的分辨率和放大比例告诉我，我来改下程序

**Comment by lovesoheart** [comment]
> 你试试看把字体调小点，分辨率调大点？ 如果还不行的话，把你用的分辨率和放大比例告诉我，我来改下程序

非常感谢您。字体大小和解析度都改过了。
我确实它是不行的。
解析度1920x1080是我日常使用的解析度。

**Comment by lovesoheart** [comment]
> > > 你试试看把字体调小点，分辨率调大点？ 如果还不行的话，把你用的分辨率和放大比例告诉我，我来改下程序
> > 
> > 
> > 非常感谢您。字体大小和解析度都改过了。 我确实它是不行的。 解析度1920x1080是我日常使用的解析度。
> 
> 了解，我会尽快更新程序~

麻烦您了。

另外一提，这个软体是否架设在您的伺服器，如果伺服器关闭就无法使用?
还是安装时候就已经内装使用者电脑内?

**Comment by x-nas** [comment]
安装后就在你的本机了，每次启动时候会联网更新，如果不更新或者无法连接我的伺服器也可以正常使用。

**Comment by lovesoheart** [comment]
> > 安装后就在你的本机了，每次启动时候会联网更新，如果不更新或者无法连接我的伺服器也可以正常使用。
> 
> 多次劳烦，非常感谢您。 一切麻烦您了! 因为我已迈入中年，对于程序比较不了解。只略懂一些内容，所以多次叨扰。非常抱歉。 希望日后还能多有机会对它研习




抱歉，发现了两个小地方
1.封包直接发送或发送列表的发送次数上限变成只能999
2.发送列表发送次数结束后，套接字无法像上版一样直接更改
我非常抱歉

**Comment by x-nas** [comment]
> > > 安装后就在你的本机了，每次启动时候会联网更新，如果不更新或者无法连接我的伺服器也可以正常使用。
> > 
> > 
> > 多次劳烦，非常感谢您。 一切麻烦您了! 因为我已迈入中年，对于程序比较不了解。只略懂一些内容，所以多次叨扰。非常抱歉。 希望日后还能多有机会对它研习
> 
> 抱歉，发现了两个小地方 1.封包直接发送或发送列表的发送次数上限变成只能999 2.发送列表发送次数结束后，套接字无法像上版一样直接更改 我非常抱歉

感谢反馈，这两个问题已修复，我会尽快安排更新，多谢支持！

**Comment by lovesoheart** [comment]
> > > > 安装后就在你的本机了，每次启动时候会联网更新，如果不更新或者无法连接我的伺服器也可以正常使用。
> > > 
> > > 
> > > 多次劳烦，非常感谢您。 一切麻烦您了! 因为我已迈入中年，对于程序比较不了解。只略懂一些内容，所以多次叨扰。非常抱歉。 希望日后还能多有机会对它研习
> > 
> > 
> > 抱歉，发现了两个小地方 1.封包直接发送或发送列表的发送次数上限变成只能999 2.发送列表发送次数结束后，套接字无法像上版一样直接更改 我非常抱歉
> 
> 感谢反馈，这两个问题已修复，我会尽快安排更新，多谢支持！

谢谢您!
待您有空再更新它。
再麻烦您修复发送次数以及更新分辨率时候讯息告知
或许未来有机会对您些许赞助，等待我未来经济宽裕。

顺便一提,
昨天忘了跟您说起文字大小
文字大小是150%
显示器解析度是1920x1080
若这些您比较不方便更动它，那么仍以您方便为提要。

只要我能顺利完整启动以及勾选滤镜选项。
谢谢您!

**Comment by x-nas** [comment]
> > > > > 安装后就在你的本机了，每次启动时候会联网更新，如果不更新或者无法连接我的伺服器也可以正常使用。
> > > > 
> > > > 
> > > > 多次劳烦，非常感谢您。 一切麻烦您了! 因为我已迈入中年，对于程序比较不了解。只略懂一些内容，所以多次叨扰。非常抱歉。 希望日后还能多有机会对它研习
> > > 
> > > 
> > > 抱歉，发现了两个小地方 1.封包直接发送或发送列表的发送次数上限变成只能999 2.发送列表发送次数结束后，套接字无法像上版一样直接更改 我非常抱歉
> > 
> > 
> > 感谢反馈，这两个问题已修复，我会尽快安排更新，多谢支持！
> 
> 谢谢您! 待您有空再更新它。 再麻烦您修复发送次数以及更新分辨率时候讯息告知 或许未来有机会对您些许赞助，等待我未来经济宽裕。
> 
> 顺便一提, 昨天忘了跟您说起文字大小 文字大小是150% 显示器解析度是1920x1080 若这些您比较不方便更动它，那么仍以您方便为提要。
> 
> 只要我能顺利完整启动以及勾选滤镜选项。 谢谢您!

已更新1.0.0.23 你试试看是否可勾选滤镜

**Comment by lovesoheart** [comment]
> > > > > > 安装后就在你的本机了，每次启动时候会联网更新，如果不更新或者无法连接我的伺服器也可以正常使用。
> > > > > 
> > > > > 
> > > > > 多次劳烦，非常感谢您。 一切麻烦您了! 因为我已迈入中年，对于程序比较不了解。只略懂一些内容，所以多次叨扰。非常抱歉。 希望日后还能多有机会对它研习
> > > > 
> > > > 
> > > > 抱歉，发现了两个小地方 1.封包直接发送或发送列表的发送次数上限变成只能999 2.发送列表发送次数结束后，套接字无法像上版一样直接更改 我非常抱歉
> > > 
> > > 
> > > 感谢反馈，这两个问题已修复，我会尽快安排更新，多谢支持！
> > 
> > 
> > 谢谢您! 待您有空再更新它。 再麻烦您修复发送次数以及更新分辨率时候讯息告知 或许未来有机会对您些许赞助，等待我未来经济宽裕。
> > 顺便一提, 昨天忘了跟您说起文字大小 文字大小是150% 显示器解析度是1920x1080 若这些您比较不方便更动它，那么仍以您方便为提要。
> > 只要我能顺利完整启动以及勾选滤镜选项。 谢谢您!
> 
> 已更新1.0.0.23 你试试看是否可勾选滤镜

太感谢您了
能显示勾选框了。
我只要能先把字体缩回100%就可以完美执行。
我再使用它研习看看是不是还有其他疑问。
真的非常感谢您
未来会有答谢您的一天的
