### ISSUE TITLE
请问有QQ交流群之类的沟通渠道吗？

### ISSUE THREAD

**Issue by jinghaifeng1** [x-nas/WinPacketsEdit#7]
如题。
另外，我看到了作者在吾爱受到的不公正待遇的申诉帖子，整个过程把我看笑了，作者不用这么卑微。我支持你。版主他们根本不懂什么是微软的ClickOnce发布技术。甚至都不愿意点开看一眼。高傲的小丑。

**Comment by jinghaifeng1** [comment]
我看到了你满腔的开源热血和激情，加油！

**Comment by jinghaifeng1** [comment]
作者大大，为了表达我对你的敬意和开源精神，同时也为了声援你在吾爱受到的不公正待遇，我要向你赞助。

**Comment by x-nas** [comment]
谢谢，这事已经过去了就这样结束吧，结果还是好的。

QQ群没有哦，有问题可以论坛或者github给我留言都可以哈

**Comment by jinghaifeng1** [comment]
> 谢谢，这事已经过去了就这样结束吧，结果还是好的。
> 
> QQ群没有哦，有问题可以论坛或者github给我留言都可以哈

好吧

**Comment by Zjzjzjzjs** [comment]
可否留个联系方式，什么的，我想找你定制一个，也算支持一下你。
